#ifndef INCLUDE_VERSION_H
#define INCLUDE_VERSION_H

#define STRINGIFY_(X) #X
#define STRINGIFY(X) STRINGIFY_(X)

#define VERSION_STRING \
	STRINGIFY(VERSION_MAJOR) "." STRINGIFY(VERSION_MINOR) "." STRINGIFY(VERSION_PATCH)

#endif // INCLUDE_VERSION_H
